[tool.poetry]
name = "simple-https-server"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
gunicorn = "^23.0.0"
Flask = "^2.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
